version: '3.8'

services:
  ihrp-chatbot:
    build: .
    ports:
      - "7860:7860"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    volumes:
      - ./feedback.db:/app/feedback.db
      - ./content_hashes.json:/app/content_hashes.json
      - ./qdrant_local:/app/qdrant_local
    restart: unless-stopped